### ISSUE TITLE
Telephone Extraction Button Doesn't Appear to Work

### ISSUE THREAD

**Issue by Bowiemb** [giTorto/extraCTU-plugin#1]
Everything else seems to work just fine; however, when I select a country of origin and select "Extract Telephone Number", nothing happens. 

Any advice?

Thank you!
My best,
Michael

**Comment by giTorto** [comment]
Hi,
It's hard to say without any further information. 
It's a bit hard to me to debug it as of know, but I can tell you where you can find the error most likely.
If nothing seems to happen, I would guess the error is in the front end.
**On the client side**, the main difference is related to the selection of the country, in the function defined at https://github.com/giTorto/extraCTU-plugin/blob/d958760ce717da3529606a282ccfeeec84353574/module/dialogs/extraction.js#L65

The client side error should be easy to detect just showing the javascript console and seeing if there is an error when clicking on "Extract Telephone Number".

**To test the server side**, can you try with different origins, such as Italy, U.S., whatever? 
The implementation of the Italian telephone numbers extraction is mostly based on a regex, whereas for other countries is mostly based on the telephone-number library by google.

On the server side, All features share the most part of the code.
The only main difference between extraction of Telephone numbers, urls and e-mails is in in the function call at https://github.com/giTorto/extraCTU-plugin/blob/d958760ce717da3529606a282ccfeeec84353574/src/org/extraction/services/Operazione.java#L71 

The function is defined at https://github.com/giTorto/extraCTU-plugin/blob/d958760ce717da3529606a282ccfeeec84353574/src/org/extraction/services/Operazione.java#L121

Thank you for your help

My best,
Giuliano

**Comment by Bowiemb** [comment]
Yes, sir. The Javascript console printed out the following error:

project-bundle.js:41604 Uncaught ReferenceError: getSelectedText is not defined
    at Dialog.extract (project-bundle.js:41604)
    at HTMLButtonElement.<anonymous> (project-bundle.js:41556)
    at HTMLButtonElement.dispatch (project-bundle.js:4643)
    at HTMLButtonElement.elemData.handle (project-bundle.js:4311)

**Comment by giTorto** [comment]
Interesting, I have just added the above mentioned function. 
Can you try to build it again and let me know whether it solved the issue?

**Comment by Bowiemb** [comment]
That fixed it! Thank you, sir. 

My best,
Michael
